include:
  - assets/style.css


description: "Postdoctoral Researcher â€” Dynamical Systems & Ergodic Theory"
#theme: minima
theme: jekyll-theme-minimal

markdown: kramdown
#author:email: "nicolo (dot) paviato (at) gmail (dot) com"

plugins:
  - jekyll-feed

<style>
  a:hover {
    color: #0056b3;
    text-decoration: underline;
  }
</style>
