title: "Nicolò Paviato"
description: "Postdoctoral Researcher — Dynamical Systems & Ergodic Theory"
theme: minima

markdown: kramdown
author:
  email: "nicolo (dot) paviato (at) gmail (dot) com"

plugins:
  - jekyll-feed
